apiVersion: skaffold/v2beta8
kind: Config
deploy:
  kubectl:
    manifests:
      - "./k8s/*"
build:
  artifacts:
    - image: aitops/building-blocks-auth
      docker:
        dockerfile: prod.Dockerfile
